// "use client"

// import {BrowserRouter} from 'react-router-dom'
// import Nav from '@/components/navigation/nav'
// import RouterView from '@/components/navigation/routerView'
// import NextNav from '@/components/navigation/nextNav'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Frontend App",
  description: "Generated by create next app",
};

import ClientNavLayout from '@/components/navigation/ClientNavLayout';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientNavLayout>{children}</ClientNavLayout>

        {/* MENGGUNAKAN REACT ROUTER DOM */}
        {/* <BrowserRouter>
          <Nav/>
          <RouterView/>
        </BrowserRouter> */}
      </body>
    </html>
  );
}
